apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: todo-app-runner
spec:
  replicas: 1
  template:
    spec:
      repository: siddarthsurana/Go-App
      labels:
        - self-hosted
        - linux
        - x64
      env:
        - name: ARGOCD_SERVER
          value: "argocd-server.argocd.svc.cluster.local"
        - name: ARGOCD_APP_NAME
          value: "todo-app"