redis-ha:
  enabled: false
controller: 
  replicas: 1
server:
  replicas:1
repoServer:
  replicas: 1
applicationSet:
  replicas: 1
global:
  domain: argocd.example.com
  certificate:
    enabled: true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    
