site_name: ${{ values.app_name }}
repo_url: https://github.com/siddarthsurana/${{ values.app_name }}
site_description: A brief description of my project.
site_author: Siddarth Surana

# Navigation structure
nav:
  - Overview:
    - Getting started: docs/index.md

plugins:
  - techdocs-core